require("modules.monitors")
require("modules.binds")
require("modules.autostart")
require("modules.env")
require("modules.permissions")
require("modules.looks")
require("modules.misc")
require("modules.input")
require("modules.rules")
require("modules.layouts")
require("modules.animations")

