-- Generated by nwg-displays on 2026-08-09 at 12:50:32. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1080@180.0",
    position = "0x400",
    scale = 1.0
})
hl.monitor({
    output = "eDP-1",
    mode = "3200x2000@165.0",
    position = "2560x0",
    scale = 2
})
