-- Custom Bezier Curves (all fluid, no overshoot)
hl.curve("Linear", { type = "bezier", points = { {0.00, 0.00}, {1.00, 1.00} } })
hl.curve("Glide", { type = "bezier", points = { {0.22, 0.61}, {0.36, 1.00} } })
hl.curve("Drift", { type = "bezier", points = { {0.16, 0.68}, {0.43, 0.99} } })
hl.curve("Ripple", { type = "bezier", points = { {0.25, 0.46}, {0.45, 0.94} } })
hl.curve("Wave", { type = "bezier", points = { {0.37, 0.00}, {0.63, 1.00} } })
hl.curve("Melt", { type = "bezier", points = { {0.11, 0.00}, {0.29, 1.00} } })
hl.curve("Pour", { type = "bezier", points = { {0.42, 0.00}, {0.58, 1.00} } })
hl.curve("Stream", { type = "bezier", points = { {0.19, 0.02}, {0.32, 0.97} } })
hl.curve("Current", { type = "bezier", points = { {0.33, 0.15}, {0.20, 0.93} } })
hl.curve("Settle", { type = "bezier", points = { {0.08, 0.55}, {0.32, 1.00} } })
hl.curve("Ease", { type = "bezier", points = { {0.45, 0.05}, {0.55, 0.95} } })

-- Custom Spring (critically damped — no bounce)
hl.curve("Calm", { type = "spring", mass = 1, stiffness = 60, dampening = 22 })

-- Animation Leafs
hl.animation({ leaf = "border", enabled = true, speed = 4, bezier = "Stream" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "Glide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "Drift", style = "slide left 30%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "Settle", style = "slide right 30%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 4, bezier = "Melt" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 4, bezier = "Melt" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 5, bezier = "Ripple" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 6, bezier = "Current" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 6, bezier = "Pour" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 6, bezier = "Pour" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 6, bezier = "Wave", style = "slidehoriz" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 5, bezier = "Drift", style = "slidefadehoriz 40%" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 5, bezier = "Drift", style = "slidefadehoriz 40%" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 4, bezier = "Ease" })